version: "3.1"
services:
  # Nginx Reverse Proxy container
  nginx:
    image: nginx:alpine
    # Bind ports 80 and 443 to the host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Copy configuration file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Mount app directory to the nginx container to serve static files
      - ./app/:/var/www
    depends_on:
      - app
  app:
    # PHP-FPM container
    build: 
       context: ./php
       dockerfile: Dockerfile
    cap_add:
      - ALL
    volumes:
      # Mount app directory to php-fpm
      - ./app:/var/www
    depends_on:
      - db
  db:
    # MariaDB database container
    # Hosts are mapped internally between containers
    # i.e: Host connects to MariaDB via 127.0.0.1:3306, Other containers connect using db:3306 
    image: mariadb
    environment:
      # MySQL root account password
        MYSQL_ROOT_PASSWORD: passwordhere
    volumes:
      # Create named volume for database persistance
      # Volume types: https://success.docker.com/article/different-types-of-volumes
      - db:/var/lib/mysql
    ports:
      # Open port 3306 to allow GUI interfaces to connect to the database.
      # Disable on production.
      - '3306:3306'
  mailhog:
    # Mailhog container to trap mail during development
    image: mailhog/mailhog:v1.0.0
    ports:
      # SMTP
      - "1025:1025"
      # The GUI is accessed at 127.0.0.1:8025
      - "8025:8025"
volumes:
  db:




